### PR TITLE
Redux store implementation

### PR DESCRIPTION
**Pull request by glaubinix**
I was playing around a bit with this and decided to try using redux as a frame storage. Feel free to close this PR if you think this is too much.

What this fixes:
* proper implementation of reset
* removing the last frame now updates the shadow (previously the removed image shadow would stay)

Reasons why I was doing this aka future possible features:
* adjust the delay for frames after they were added
* adjust caption for frames after they were added
* play around with filters (can create copy of the canvas in the render method and apply filter inside render)

Why this is still WIP:
* ~~pretty sure this has tons of memory leaks when frames are removed~~
* ~~needs some more cleanup~~
* not sure how this performs on mobile

Any thoughts on this @rwos?

### CODE REVIEW

**Comment by rwos** [comment]
*Really* not sure if you're trolling 😄 

If not: yeah, if it makes main.js look a bit less shitty (and it seems it has that potential), I'm all for it.

Maaaaybe it's possible to re-implement the redux store though, so we don't end up with half the internet as dependencies (just using redux would be fine for now though).

**Comment by glaubinix** [comment]
No, I am not trolling. I honestly believe that go into such a direction will make it much easier to add new features without breaking existing ones.

Also would vote against re-implementing redux store. Using redux comes with additional features for free e.g. undo, redo.

**Comment by rwos** [comment]
undo/redo is a good point - maybe we can expose that to the UI at some point (I should also probably flexbox-ify this a bit)

**Comment by rwos** [comment]
Looks like the right-hand-side gif is broken again in Firefox with this (not sure about chrome, since it doesn't seem to allow the camera on file:/// URLs).

(last time, the fix was this: https://github.com/rwos/gifstopmotion/pull/14/commits/97aae788e79d8011eebcc02efd4b58c5d1122a0b)

**Comment by glaubinix** [comment]
@rwos fixed the firefox issue again. I use php server + ngrok for chrome testing.

**Comment by glaubinix** [comment]
Ok, wanted to check this with iOS Safari but had to realise that Safari does not support getUserMedia. This will work again with Safari 11 (next OS version) and maybe at some point with Mobile Safari. I guess from my side everything is in the PR that I wanted to push with it.

**Review by rwos — APPROVED** [review]
👍 I use "deploy to production" for testing ;)

**Comment by rwos** [comment]
aaand now it's broken 😄 fixing

**Comment by rwos** [comment]
Well, alright, v85 should work again - I did revert the getUserMedia stuff, that didn't seem to work for me.

**Pull request merged**
